sample_data = [
    ("en", "The quick brown fox jumps over the lazy dog.", "quick brown fox"),
    ("en", "He opened the book and started reading.", "opened the book"),
    ("en", "A storm was brewing on the horizon.", "storm"),
    ("en", "Children were playing in the park.", "playing in the park"),
    ("en", "She baked a chocolate cake for the party.", "chocolate cake"),
    ("en", "The sun dipped below the mountain.", "sun"),
    ("en", "Music filled the entire room with joy.", "Music"),
    ("en", "They adopted a puppy from the shelter.", "puppy"),
    ("en", "The artist painted a beautiful landscape.", "beautiful landscape"),
    ("en", "He studied the stars through his telescope.", "telescope"),
    
    ("vi", "Trời hôm nay rất đẹp và trong lành.", "trong lành"),
    ("vi", "Cô ấy đang học tiếng Anh mỗi ngày.", "tiếng Anh"),
    ("vi", "Anh ta mua một chiếc xe máy mới.", "xe máy"),
    ("vi", "Họ đi chơi ở Đà Lạt cuối tuần qua.", "Đà Lạt"),
    ("vi", "Con mèo đang nằm ngủ trên ghế sofa.", "Con mèo"),
    ("vi", "Chúng tôi ăn tối ở một nhà hàng Nhật.", "nhà hàng Nhật"),
    ("vi", "Bố tôi thích trồng cây trong vườn.", "trồng cây"),
    ("vi", "Cô giáo dạy học sinh rất tận tâm.", "Cô giáo"),
    ("vi", "Học sinh đang làm bài kiểm tra.", "bài kiểm tra"),
    ("vi", "Tôi thích nghe nhạc mỗi khi rảnh.", "nghe nhạc"),

    ("zh", "他正在学习中文。", "学习中文"),
    ("zh", "我们去公园散步。", "公园"),
    ("zh", "这家餐厅的面条很好吃。", "面条"),
    ("zh", "她买了一双新鞋子。", "新鞋子"),
    ("zh", "孩子们在花园里玩耍。", "玩耍"),
    ("zh", "我喜欢喝绿茶。", "绿茶"),
    ("zh", "他们正在看电影。", "看电影"),
    ("zh", "这个地方风景很美。", "风景"),
    ("zh", "请把窗户打开。", "窗户"),
    ("zh", "我每天早上跑步。", "早上跑步"),

    ("ja", "彼は毎朝ジョギングをします。", "ジョギング"),
    ("ja", "私は寿司が大好きです。", "寿司"),
    ("ja", "図書館で本を借りました。", "図書館"),
    ("ja", "猫がソファで寝ています。", "猫"),
    ("ja", "彼女はピアノを弾きます。", "ピアノ"),
    ("ja", "映画を見に行きました。", "映画"),
    ("ja", "天気がとても良いです。", "天気"),
    ("ja", "新しい服を買いました。", "新しい服"),
    ("ja", "山に登るのが好きです。", "山に登る"),
    ("ja", "彼らはレストランで夕食を食べました。", "レストラン"),

    ("ko", "그녀는 매일 아침 운동을 해요.", "운동"),
    ("ko", "나는 김치를 좋아해요.", "김치"),
    ("ko", "우리는 서울을 여행했어요.", "서울"),
    ("ko", "강아지가 소파에서 자고 있어요.", "강아지"),
    ("ko", "그는 음악을 듣는 것을 좋아해요.", "음악"),
    ("ko", "나는 새로운 책을 샀어요.", "새로운 책"),
    ("ko", "친구들과 영화관에 갔어요.", "영화관"),
    ("ko", "공원에서 산책했어요.", "산책"),
    ("ko", "비가 오고 있어요.", "비"),
    ("ko", "오늘 저녁은 불고기를 먹었어요.", "불고기"),

    # Add more English phrases
    ("en", "The lighthouse stood tall against the crashing waves.", "lighthouse"),
    ("en", "He whispered a secret to his friend.", "whispered a secret"),
    ("en", "Snow fell gently on the quiet town.", "Snow"),
    ("en", "The detective solved the mystery just in time.", "solved the mystery"),
    ("en", "She danced gracefully across the stage.", "danced gracefully"),
    ("en", "The computer crashed during the presentation.", "computer crashed"),
    ("en", "He poured a cup of hot coffee.", "hot coffee"),
    ("en", "The team celebrated their victory.", "celebrated"),
    ("en", "Books were scattered across the floor.", "Books"),
    ("en", "A rainbow appeared after the rain.", "rainbow"),

    # More Vietnamese phrases
    ("vi", "Tôi đang đọc một quyển sách hay.", "quyển sách"),
    ("vi", "Trẻ con chơi đùa ngoài sân.", "Trẻ con"),
    ("vi", "Tôi uống cà phê mỗi sáng.", "cà phê"),
    ("vi", "Cô ấy viết thư cho bạn.", "viết thư"),
    ("vi", "Chúng ta cần dọn dẹp phòng này.", "dọn dẹp"),
    ("vi", "Anh ấy sửa xe đạp trong sân.", "sửa xe đạp"),
    ("vi", "Con chó chạy quanh vườn.", "Con chó"),
    ("vi", "Bà tôi thích xem phim truyền hình.", "phim truyền hình"),
    ("vi", "Tôi đã đến thăm Hà Nội năm ngoái.", "Hà Nội"),
    ("vi", "Mẹ tôi nấu bữa ăn ngon.", "bữa ăn ngon"),

    # Optional: More Chinese/Japanese/Korean to reach 100 exactly
    ("zh", "我昨天去了博物馆。", "博物馆"),
    ("ja", "私は公園で犬と遊びました。", "犬と遊びました"),
    ("ko", "우리는 바닷가에서 놀았어요.", "바닷가"),
]
